services:
  - type: web
    name: ninja-inflatable-park
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install && npm run build --filter=web
    startCommand: cd apps/web && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
